### ISSUE TITLE
Bug: app crashed when i click on leader board 

### ISSUE THREAD

**Issue by darewealth** [cubei/FlappyCow#22]
### Describe the bug.

App crashed when I check the leaderboard after I played and loss

### Steps to reproduce.

* Launch the app.

* Sign in 

* Play the game and loss

* then check the leaderboard immediately.

### Expected Behaviour

I expect that I should be able to check the leaderboard without any issue

### Screen recording
https://youtu.be/i8yNSsyOjpY

### Devices and Versions)

* Device: [itel]

* Version [6.1]

* App version [3.3.0]

### Log
```05-06 09:00:14.820 30607 30607 E AndroidRuntime: FATAL EXCEPTION: main
05-06 09:00:14.820 30607 30607 E AndroidRuntime: Process: com.quchen.flappycow, PID: 30607
05-06 09:00:14.820 30607 30607 E AndroidRuntime: java.lang.IllegalStateException: GoogleApiClient must be connected.
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at cappycow.StartscreenView.onTouchEvent(StartscreenView.java:203)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9307)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2199)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2199)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2199)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2419)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1744)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2776)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2380)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9533)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-06 09:00:14.820 30607 30607 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by cubei** [comment]
Is this my release from the play store, or where did you get it?

**Comment by darewealth** [comment]
From play store.

**Comment by cubei** [comment]
I see from the Google Play Console that only you affected by this issue. Have you blocked internet access for the Google Services or something?
Or any other idea? Feel free to submit a pull request if you have a solution.

**Comment by darewealth** [comment]
My Google play is intact and so is my internet access. I would have like to solve it, but I can't solve the issue. But you could label it help wanted, someone might help.
